CREATE TABLE complexInHive(
empid STRING,
name STRING,
permanent_address STRUCT<house_no:INT,city:STRING,pincode:STRING>,
experience_with_domain MAP<STRING,INT>,
skill ARRAY<STRING>)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
COLLECTION ITEMS TERMINATED BY '&'
MAP KEYS TERMINATED BY ':'
STORED AS TEXTFILE;